apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    operator.iomesh.com/role: operator
    {{- include "operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "operator.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "operator.labels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: operator
        command:
        - /iomesh-controller
        args:
        {{- with .Values.extraArgs }}
        {{- toYaml . | nindent 8}}
        {{- end }}
        - operator
        - --enable-leader-election=true
        - --leader-election-namespace=$(NAMESPACE)
        - --leader-election-id={{- include "operator.name" . -}}-lock
        image: {{ include "operator.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ZBSOP_IMAGE
          value: {{ include "operator.image" . }}
      {{- with .Values.extraVolumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ include "operator.extraPersistentVolumeClaim" . }}
